/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.javaopen.kotlin.updates

import kotlinx.coroutines.*

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun hello() = GlobalScope.async {
    "Hello, async."
}

fun main(args: Array<String>) {

    println("start async function")
    runBlocking {
        println(hello().await())
    }
    println("end async function")

    // 実行結果:
    // start async function
    // Hello, async.
    // end async function

    println("start runBlocking")
    runBlocking {
        val defferd = GlobalScope.async {
            println(App().greeting)
        }
        defferd.await()
    }
    println("end runBlocking")

    // 実行結果:
    // tart runBlocking
    // Hello world.
    // end runBlocking

    println("start async")

    GlobalScope.async {
        // ノンブロッキングで実行されるため実行前にmain()が終わる
        println("Inside async")
    }
    //Thread.sleep(1000) // これがないとasync実行前にmain()が終わる
    println("end async")

    // 実行結果:
    // start async
    // end async
}
