/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.javaopen.kotlin.updates

import kotlinx.coroutines.*

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {

    println("start runBlocking")
    runBlocking {
        async {
            println(App().greeting)
        }
    }
    println("end runBlocking")

    // 実行結果:
    // tart runBlocking
    // Hello world.
    // end runBlocking

    println("start async")

    GlobalScope.async {
        // ノンブロッキングで実行されるため実行前にmain()が終わる
        println("Inside async")
    }
    //Thread.sleep(1000) // Thread.sleep()がないとasyncは実行されない
    println("end async")

    // 実行結果:
    // start async
    // end async
}
